### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by SanderGit** [vesvault/snif#1]
The certificate of snif.host expired on Sept 29.

**Comment by vesvault** [comment]
Might be because of DST Root CA X3, it has expired on 09/30/21.
Platforms that don't have ISRG Root X1 in the trust root have this problem with all certs issued by Let's Encrypt.
Which platform are you using? Do you have problems opening https://letsencrypt.org ?

**Comment by SanderGit** [comment]
Any browser on IOS 15. Got the said warning once, other browsers only show that the connection is not secure.
But I think I’m not the only one looking at [this report](https://dev.ssllabs.com/ssltest/analyze.html?d=snif.host&s=104.131.120.15).

**Comment by vesvault** [comment]
I just tried on 2 different iOS 15 devices, worked fine, no warnings.
Might've been some cache issues. Let me know if you still see any problems, and thanks a lot for the heads up!
Yes I know, the ssllabs report grades https://snif.host at B, I didn't disable a few older protocols to avoid issues with older platforms, since snif.host is not hosting any sensitive content.
